import Navbar from '@/companets/navbar/Navbar'
import style from'./globals.css'
import { Inter, Roboto, Poppins } from 'next/font/google'
import Footer from '@/companets/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={style.container}>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html >
  )
}
